version: 2
jobs:
  build:
    working_directory: ~/jest-tests-playground
    docker:
      - image: circleci/node:10.15.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm i -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-dependencies
          command: npm i
      - save_cache: 
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test:unit
      - run:
          name: code-coverage
          command: npm run test:unit -- --collectCoverage=true
      - run:
          name: code-coverage-junit-reporter
          command: npm run test:unit -- --ci --runInBand --reporters=default --reporters=jest-junit
          environment:
            JEST_JUNIT_OUTPUT: "coverage/results.xml"
      - store_test_results:
          path: coverage